### ISSUE TITLE
swoole 怎么开启多端口映射

### ISSUE THREAD

**Issue by Felo-Z** [yeszao/dnmp#136]
laravel5.8+[laravels](https://github.com/hhxsv5/laravel-s)，swoole成功启动后无法实现ws端口映射

**Comment by skylei** [comment]
@Felo-Z 
在docker-compose.yml配置的php节点增加ports端口配置：
![image](https://user-images.githubusercontent.com/1855591/57433591-73b7c000-726b-11e9-9824-48e181b9d0b8.png)
--------

**Comment by Felo-Z** [comment]
![1](https://user-images.githubusercontent.com/6071340/57433865-2556f100-726c-11e9-9f6b-75dc4737e4fc.png)
![2](https://user-images.githubusercontent.com/6071340/57433869-25ef8780-726c-11e9-99dc-d1cebffc7870.png)
我的docker-compose.yml和nginx配置，
ng负载均衡那里，按照lavevels作者的文档配置两种写法
`server 127.0.0.1:5200 weight=5 max_fails=3 fail_timeout=30s;`
`server php72:5200 weight=5 max_fails=3 fail_timeout=30s;`
均不能正常访问，dnmp和laravels都正常访问

**Comment by Felo-Z** [comment]
> ## @Felo-Z
> 在docker-compose.yml配置的php节点增加ports端口配置：
> ![image](https://user-images.githubusercontent.com/1855591/57433591-73b7c000-726b-11e9-9824-48e181b9d0b8.png)

你的可以正常访问吗，swoole搭建的websocket

**Comment by yuhal** [comment]
```
php56:
    build:
     context: ./services/php
     args:
       PHP_VERSION: php:${PHP56_VERSION}-fpm-alpine
       CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
       PHP_EXTENSIONS: ${PHP56_EXTENSIONS}
       TZ: "$TZ"
    container_name: php56
    ports:
     - "9501:9501"
     - "9502:9502"
    volumes:
     - ${SOURCE_DIR}:/www/:rw
     - ${PHP56_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
     - ${PHP56_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
     - ${PHP56_LOG_DIR}:/var/log/php
     - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
     - SYS_PTRACE
    networks:
     - default
```
这样配置后，swoole链接成功啦～

**Comment by ShuiPingYang** [comment]
只需要做两步,第一,在yml里面配置暴露的端口号;
第二步,写好nginx配置文件即可.

### yml配置:
```yml

  php:
    build:
      context: ./services/php
      args:
        PHP_VERSION: php:${PHP_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        TZ: "$TZ"
    container_name: php
    ports:
      - "9501:9501"
      - "9502:9502"
      - "9503:9503"
      - "9504:9504"
      - "9505:9505"
      - "9506:9506"
    extra_hosts:
      - "www.site1.com:172.17.0.1"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default
 ```

### nginx配置
```nginx
server {
    listen       9502;
    server_name  xxxx.test *.xxxx.test;
    root   /www/xxxx;
    index  index.php index.html index.htm;
    #charset koi8-r;
    
    access_log /dev/null;
    #access_log  /var/log/nginx/nginx.xxxx.access.log  main;
    error_log  /var/log/nginx/nginx.xxxx.error.log  warn;
    
    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}

server {
    listen 443 ssl http2;
    server_name xxxx.test *.xxxx.test;
    root   /www/xxxx;
    index  index.php index.html index.htm;
    #charset koi8-r;

    access_log /dev/null;
    #access_log  /var/log/nginx/nginx.xxxx.access.log  main;
    error_log  /var/log/nginx/nginx.xxxx.error.log  warn;

    #error_page  404              /404.html;

    ssl_certificate /ssl/localhost/localhost.crt;
    ssl_certificate_key /ssl/localhost/localhost.key;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }


    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}


```
