### ISSUE TITLE
安装swoole扩展之后，127.0.0.1:9501拒绝访问

### ISSUE THREAD

**Issue by abccj2** [yeszao/dnmp#194]
## 安装swoole扩展之后，127.0.0.1:9501拒绝访问

**Comment by humour-picasso** [comment]
> ## 安装swoole扩展之后，127.0.0.1:9501拒绝访问

请问你的问题解决了吗，我遇到了同样的问题，建立的tcp连接只能在容器内部访问，本地请求127.0.0.1:9501连接拒绝

**Comment by humour-picasso** [comment]
> ## 安装swoole扩展之后，127.0.0.1:9501拒绝访问

请问你的问题解决了吗，我遇到了同样的问题

**Comment by ShuiPingYang** [comment]
只需要做两步,第一,在yml里面配置暴露的端口号;
第二步,写好nginx配置文件即可.

### yml配置:
```yml

  php:
    build:
      context: ./services/php
      args:
        PHP_VERSION: php:${PHP_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        TZ: "$TZ"
    container_name: php
    ports:
      - "9501:9501"
      - "9502:9502"
      - "9503:9503"
      - "9504:9504"
      - "9505:9505"
      - "9506:9506"
    extra_hosts:
      - "www.site1.com:172.17.0.1"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default
 ```

### nginx配置
```nginx
server {
    listen       9502;
    server_name  xxxx.test *.xxxx.test;
    root   /www/xxxx;
    index  index.php index.html index.htm;
    #charset koi8-r;
    
    access_log /dev/null;
    #access_log  /var/log/nginx/nginx.xxxx.access.log  main;
    error_log  /var/log/nginx/nginx.xxxx.error.log  warn;
    
    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}

server {
    listen 443 ssl http2;
    server_name xxxx.test *.xxxx.test;
    root   /www/xxxx;
    index  index.php index.html index.htm;
    #charset koi8-r;

    access_log /dev/null;
    #access_log  /var/log/nginx/nginx.xxxx.access.log  main;
    error_log  /var/log/nginx/nginx.xxxx.error.log  warn;

    #error_page  404              /404.html;

    ssl_certificate /ssl/localhost/localhost.crt;
    ssl_certificate_key /ssl/localhost/localhost.key;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }


    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}


```
