### ISSUE TITLE
安装swoole扩展之后，本机链接不上，是端口未映射的原因吗？

### ISSUE THREAD

**Issue by HFLZRH** [yeszao/dnmp#310]
php swoole 扩展

Swoole | enabled
-- | --
Author | Swoole Team <team@swoole.com>
Version | 4.5.2
Built | Aug 10 2020 17:40:26
coroutine | enabled
epoll | enabled
eventfd | enabled
signalfd | enabled
spinlock | enabled
rwlock | enabled
mutex_timedlock | enabled
pthread_barrier | enabled
async_redis | enabled

服务端源码，使用9502端口

index.php 

//创建WebSocket Server对象，监听0.0.0.0:9502端口
$ws = new Swoole\WebSocket\Server('0.0.0.0', 9502);

//监听WebSocket连接打开事件
$ws->on('open', function ($ws, $request) {
    var_dump($request->fd, $request->server);
    $ws->push($request->fd, "hello, welcome\n");
});

//监听WebSocket消息事件
$ws->on('message', function ($ws, $frame) {
    echo "Message: {$frame->data}\n";
    $ws->push($frame->fd, "server: {$frame->data}");
});

//监听WebSocket连接关闭事件
$ws->on('close', function ($ws, $fd) {
    echo "client-{$fd} is closed\n";
});

$ws->start();

php  index.php 

前端链接WebSocket

demo.html

var wsServer = 'ws://192.168.0.1:9502';
    var websocket = new WebSocket(wsServer);
    websocket.onopen = function (evt) {
        console.log("Connected to WebSocket server.");
    };

    websocket.onclose = function (evt) {
        console.log("Disconnected");
    };

    websocket.onmessage = function (evt) {
        console.log('Retrieved data from server: ' + evt.data);
    };

    websocket.onerror = function (evt, e) {
        console.log('Error occured: ' + evt.data);
    };

提示错误如下

demo.html:12 WebSocket connection to 'ws://192.168.0.1:9502/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
(anonymous) @ demo.html:12
demo.html:26 Error occured: undefined
demo.html:18 Disconnected

**Comment by jingmian** [comment]
`docker ps`就查看出端口是否有映射出来了,没有映射出来,就在`docker-composer.yml`添加就可以了

**Comment by HFLZRH** [comment]
> `docker ps`就查看出端口是否有映射出来了,没有映射出来,就在`docker-composer.yml`添加就可以了

4d653ec50ae4        dnmp_php            "docker-php-entrypoi…"   37 minutes ago      Up 2 minutes        9000/tcp, 9501/tcp                         php

显示开通9501端口 ，我的服务端口也改成9501 但还是连不上

**Comment by jingmian** [comment]
你这个只是开启容器端口,要设置成这种格式才对`0.0.0.0:9501->9501/tcp`

**Comment by HFLZRH** [comment]
> 你这个只是开启容器端口,要设置成这种格式才对`0.0.0.0:9501->9501/tcp`

好的 谢谢  问题已经解决

**Comment by ShuiPingYang** [comment]
只需要做两步,第一,在yml里面配置暴露的端口号;
第二步,写好nginx配置文件即可.

### yml配置:
```yml

  php:
    build:
      context: ./services/php
      args:
        PHP_VERSION: php:${PHP_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        TZ: "$TZ"
    container_name: php
    ports:
      - "9501:9501"
      - "9502:9502"
      - "9503:9503"
      - "9504:9504"
      - "9505:9505"
      - "9506:9506"
    extra_hosts:
      - "www.site1.com:172.17.0.1"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default
 ```

### nginx配置
```nginx
server {
    listen       9502;
    server_name  xxxx.test *.xxxx.test;
    root   /www/xxxx;
    index  index.php index.html index.htm;
    #charset koi8-r;
    
    access_log /dev/null;
    #access_log  /var/log/nginx/nginx.xxxx.access.log  main;
    error_log  /var/log/nginx/nginx.xxxx.error.log  warn;
    
    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}

server {
    listen 443 ssl http2;
    server_name xxxx.test *.xxxx.test;
    root   /www/xxxx;
    index  index.php index.html index.htm;
    #charset koi8-r;

    access_log /dev/null;
    #access_log  /var/log/nginx/nginx.xxxx.access.log  main;
    error_log  /var/log/nginx/nginx.xxxx.error.log  warn;

    #error_page  404              /404.html;

    ssl_certificate /ssl/localhost/localhost.crt;
    ssl_certificate_key /ssl/localhost/localhost.key;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }


    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}


```
