### ISSUE TITLE
php容器访问nginx的server的问题

### ISSUE THREAD

**Issue by xuexuguang** [yeszao/dnmp#347]
问题：
如何在php的容器里访问nginx容器里部署的server,除了直接进入php的容器，将nginx的server解析到php容器的hosts里，还有别的办法吗？
每次容器重启完之后，就得重新解析一次hosts，有啥好的办法吗？

**Comment by l12ab** [comment]
要手动指定nginx容器的ip，php容器的ip。并在php容器配置里，增加extra_hosts

nginx容器添加
```
networks:
      net-default:
        ipv4_address: 10.0.0.10
```
php容器
```
extra_hosts:
      - "yourdomain.com:10.0.0.10"
networks:
      net-default:
        ipv4_address: 10.0.0.11
```

compose底部加
```
networks:
  net-default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/24
```
