### ISSUE TITLE
mysql8 为什么非正确密码都能登陆？

### ISSUE THREAD

**Issue by SemiThin** [yeszao/dnmp#422]
环境：win10,wsl2

docker-compose mysql sh
mysql -u root -p 
无论输入什么，或者空密码直接回车都能登陆
请问这是为什么
查看mysql 库
都没有user表
![image](https://user-images.githubusercontent.com/12593507/131322099-49080cbf-e406-4a4c-a58c-b21e8df5fa7a.png)

**Comment by SemiThin** [comment]
当我注释掉mysql 映射的配置文件 一切就正常了
![image](https://user-images.githubusercontent.com/12593507/131429893-6cfba534-a209-4209-8f24-dc08c8a00d20.png)

![Uploading image.png…]()

**Comment by SemiThin** [comment]
@jingmian

**Comment by jingmian** [comment]
8.0使用这个配置
```sh
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"
```

用5.7需要用这个配置
```
  mysql5:
    image: mysql:${MYSQL5_VERSION}
    container_name: mysql5
    ports:
      - "${MYSQL5_HOST_PORT}:3306"
    volumes:
      - ${MYSQL5_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql5:/var/lib/mysql/:rw
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL5_ROOT_PASSWORD}"
      TZ: "$TZ"
```
而且你`${MYSQL5_CONF_FILE}:`与`${MYSQL_CONF_FILE}:`都搞错了,等于你用8.0的配置启动5.7版本
