### ISSUE TITLE
苹果系统下mysql无限重启提示Operation not permitted权限问题(已解决)

### ISSUE THREAD

**Issue by muzidudu** [yeszao/dnmp#426]
> mysql5    | chown: changing ownership of '/var/lib/mysql/._.gitignore': Operation not permitted
mysql5    | chown: changing ownership of '/var/lib/mysql/._auto.cnf': Operation not permitted
mysql5    | chown: changing ownership of '/var/lib/mysql/._ca-key.pem': Operation not permitted
mysql5    | chown: changing ownership of '/var/lib/mysql/._ca.pem': Operation not permitted
mysql5    | chown: changing ownership of '/var/lib/mysql/._client-cert.pem': Operation not permitted
mysql5    | chown: changing ownership of '/var/lib/mysql/._client-key.pem': Operation not permitted
mysql5    | chown: changing ownership of '/var/lib/mysql/._ib_buffer_pool': Operation not permitted
mysql5    | chown: changing ownership of '/var/lib/mysql/._ib_logfile0': Operation not permitted

docker-compose.yml 文件里的mysql配置项增加
`user: mysql`
如

```
mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    cap_add:
      - SYS_NICE
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql:/var/lib/mysql/:rw
    restart: always
    user: mysql
    privileged: true
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"
```
