### ISSUE TITLE
mac m1 mysql8 配置不生效

### ISSUE THREAD

**Issue by phpluo** [yeszao/dnmp#455]
m1  现在网上找了一圈好像只有mysql8以上的版本支持
今天想改一下sql_mode 发现挂载的配置路径`/etc/mysql/conf.d/mysql.cnf`不生效，文件是正常挂载了，
却使用默认的`/etc/my.cnf`
不知道具体原因，网上找了一圈也没有解决，文件权限也是对的mysql.conf 644，
换了几次mysql镜像和和 重新build也没有解决。
后面就想着直接挂载到默认配置文件就好了。不知道有没有遇到相同问题的。可以试一试

```
  mysql:
    image: mysql/mysql-server:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/my.cnf:ro
      - ${DATA_DIR}/mysql:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "${MYSQL_ROOT_HOST}"
      TZ: "$TZ"
```
