### ISSUE TITLE
用PHP8.2或其它版本的一个简单方法

### ISSUE THREAD

**Issue by lifetin** [yeszao/dnmp#559]
直接在.env文件将PHP_VERSION=8.2.8
这样就行了. 如果是默认安装后再想修改,需要把之前编译的全删掉
docker-compose rm

docker ps -a 
找到PHP的相关ID,删掉docker rm xxxxxxxxxx
再来
docker rmi www_php
docker rm php
再重新docker-compose up

**Comment by lifetin** [comment]
我就这么干的 ,新安装的直接改env就行.

这是结果
PHP版本：8.2.8
Nginx版本：nginx
MySQL服务器版本：8.0.28
Redis服务器版本：5.0.3
MongoDB服务器版本：MongoDB 扩展未安装 ×

**Comment by jeeinn** [comment]
建议是将 `docker-compose.yml` 文件的 php80 相关容器服务模块注释打开稍作修改即可(可查看php官方镜像tag)。这样可以有单独的容器出来和原有的php7相互隔离
```
php80:
    build:
      context: ./services/php80
      args:
        # PHP_VERSION: php:${PHP80_VERSION}-fpm-alpine3.13
        PHP_VERSION: php:8.2.2-fpm-alpine3.17
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP80_EXTENSIONS}
        TZ: "$TZ"
    container_name: php80
    ...
```
