### ISSUE TITLE
PHP代码中使用curl重启docker，nginx的IP会变

### ISSUE THREAD

**Issue by fengke549015** [yeszao/dnmp#91]
我下windows环境下配置了docker,安装DNMP成功，环境启动一切正常，但是需要一个功能使用curl功能，采用您说的方法后，可以设置成功，但是重启docker后,nginx的IP地址会改变，必须再重新设置，我这边应该如何配置可以使nginx的IP固定呢？

**Comment by yeszao** [comment]
可以配置静态IP。
在docker-compose.yml中。
首先，配置虚拟网卡driver和subnet：
```
networks:
  net-default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/24
```
然后设置nginx的静态IP：
```
  nginx:
    #其他配置...
    networks:
      net-default:
        ipv4_address: 10.0.0.10
```
再在php中设置extra_hosts：
```
  php54:
    #其他配置...
    extra_hosts:
      - "project.com:10.0.0.10"
    networks:
      - net-default
```
最后重新build一下，就OK了。
